name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    env:
      DISABLE_EMAIL_SENDING: true
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - name: Use Node.js 22 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Show pnpm version
        run: pnpm -v
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test

  playwright-tests:
    runs-on: ubuntu-latest
    env:
      DISABLE_EMAIL_SENDING: true
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run end-to-end tests
        run: pnpm test:e2e
      - name: Upload test results (HTML report)
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
